export const SET_CUR_PAGE = 'SET_CUR_PAGE';
export const FETCH_START = 'FETCH_START';
export const FETCH_DONE = 'FETCH_DONE';
export const FETCH_FAIL = 'FETCH_FAIL';
export const UPDATE_STORE_SETTINGS = 'UPDATE_STORE_SETTINGS';
export const UPDATE_FORM_STATUS = 'UPDATE_FORM_STATUS';
export const INPUT_SET_VALIDATION_STATUS = 'INPUT_SET_VALIDATION_STATUS';
export const INPUT_SET_VALUE = 'INPUT_SET_VALUE';
